# Generated by Django 5.2.8 on 2025-11-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Port',
        ),
    ]
