# Generated by Django 5.2.8 on 2025-11-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_certificate_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
